# 객체지향(Object Oriented) 프로그래밍

    1. 객체가 가진 데이터를 클래스의 속성(Attribute)이라 부르고 객체가 갖는 기능을 메서드(Method)라고 부른다.

#### 클래스(Class)

    1. 사용자 정의 객체를 만들기 위한 뼈대      
    ex) class ClassName:            # 클래스명은 주로 PascalCase를 씀.
            def method_name(self):
                method_body

            class_body
            ...
    2. 객체(Object)? 인스턴스(instance)?
        2.1. 단어 하나만 활용할 때 사용하는 것을 '객체'
        2.2. 리스트 클래스로 만들어진 '인스턴스'
        2.3. 결국 둘은 같은 말
    3. 메서드(Method)
        3.1. 클래스 바디 안에서 정의되는 함수
        ex) class ClasName:
                def method_name(self):      # 메서드를 선언할때, 첫번째 인자로 인스턴스 객체(self)를 받는다.
                    method_body

                class_body
        3.2. 클래스 속성(Attribute)
            : __init__매서드 안에서 self.속성에 값을 할당하면 됨.
            3.2.1 __init__ 메서드는 소괄호를 붙여서 인스턴스를 만들 때 호출되는 특별한 메서드(special method, magic method)
            3.2.2 __init__은 initialize의 줄임말로 인스턴스(객체)를 초기화
            3.2.3 밑줄 두개(__, double under, 던더)가 양 옆으로 붙어있는 매서드는 파이썬이 자동으로 호출하는 매서드

    4. self
        4.1. 인스턴스 

    5. 비공개 속성 사용하기
        5.1 인스턴스.속성 = 값을 통해 새롭게 인스턴스의 속성값을 변경 못하도록 막고 싶을 떄는 비공개 속성을 사용하면 됨. 
            ex) self.__attr2

    6. 클래스 매서드(@classmethod)
    
    7. 스태틱 매서드(@staticmethod)

In [2]:
class Student:
    pass

In [3]:
# 클래스로부터 인스턴스 초기화
stu_a = Student()   # 인스턴스(stu_a)은 독립적으로 존재
stu_b = Student()   # 인스턴스(stu_b)은 독립적으로 존재

stu_a.hello = "안녕하세요."     # stu_a에 대한 속성을 입력
stu_a.name = "학생A"          # stu_a에 대한 속성을 입력

In [4]:
print(stu_a.hello)
print(stu_a.name)

안녕하세요.
학생A


In [5]:
print(stu_b.hello)

AttributeError: 'Student' object has no attribute 'hello'

In [6]:
class Student:
    def __init__(self):
        self.hello = "안녕하세요."          # 모든 Student에 같은 속성을 적용하고 싶을때 self라는 인스턴스에 .hello라는 속성을 입혀준다.

    def greeting(self):
        print(self.hello)

In [7]:
stu_c = Student()

print(stu_c.hello)

안녕하세요.


In [8]:
stu_a = Student()
stu_b = Student()

stu_a.greeting()
stu_b.greeting()

안녕하세요.
안녕하세요.


In [9]:
class Person:
    def __init__(self, name, age):             # Person이라는 클래스에 인스턴스 속성이 입력
        self.name = name
        self.age = age

In [10]:
p1 = Person("name1", 40)
p2 = Person("name2", 32)

In [11]:
print(p1.__dict__)
print(p2.__dict__)

{'name': 'name1', 'age': 40}
{'name': 'name2', 'age': 32}


In [12]:
class Person2:
    def __init__(self, name, age, address):
        self.hello = "안녕하세요"
        self.name = name
        self.age = age
        self.address = address

    def greeting(self):
        print(f'{self.hello} 제 이름은 {self.name} 입니다.')

In [13]:
maria = Person2("마리아", 23, "서울시 마포구")
maria.greeting()

print(maria.__dict__)

안녕하세요 제 이름은 마리아 입니다.
{'hello': '안녕하세요', 'name': '마리아', 'age': 23, 'address': '서울시 마포구'}


In [14]:
class Person2:
    def __init__(self, name, age, address, number):
        self.name = name
        self.age = age
        self.address = address
        self.number = number

    def information(self):
        print(f'이름은 무엇인가요?: {self.name}')
        print(f'나이는 무엇인가요?: {self.age}')
        print(f'주소는 무엇인가요?: {self.address}')
    
    def numbering(self):
        print(f'{self.number} 이름: {self.name}')
        print(f'{self.number} 나이: {self.age}')
        print(f'{self.number} 주소: {self.address}')

In [15]:
maria = Person2("마리아", 20, "서울시 강남구", "첫번째")
james = Person2("제임스", 21, "서울시 구로구", "두번째")

maria.information()
james.information()
maria.numbering()
james.numbering()

이름은 무엇인가요?: 마리아
나이는 무엇인가요?: 20
주소는 무엇인가요?: 서울시 강남구
이름은 무엇인가요?: 제임스
나이는 무엇인가요?: 21
주소는 무엇인가요?: 서울시 구로구
첫번째 이름: 마리아
첫번째 나이: 20
첫번째 주소: 서울시 강남구
두번째 이름: 제임스
두번째 나이: 21
두번째 주소: 서울시 구로구


In [16]:
maria = Person2("마리아", 20, "서울시 강남구", "첫번째")
james = Person2("제임스", 21, "서울시 구로구", "두번째")

{maria, james}.information()            # set, dict, list, tuple의 형태로 인스턴스를 모을수 없음.

AttributeError: 'set' object has no attribute 'information'

In [37]:
class Person3:
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet         # 비공개 속성

    def greeting(self):
        print(f'{self.hello} 제 이름은 {self.name} 입니다.')

    def amount(self):
        print(self.__wallet)

In [39]:
kms = Person3("김민수", 95, "인천", 20000)

print(kms.name)
print(kms.age)
print(kms.address)
print(kms.__wallet)     # 외부에서는 비공개 속성은 접근할 수 없음.

김민수
95
인천


AttributeError: 'Person3' object has no attribute '__wallet'

In [40]:
kms.amount()        # 비공개 속성은 다른 정의를 추가하여 우회접근이 가능하다.

20000


In [59]:
class Person4:
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet         # 비공개 속성

    def amount(self):
        print(self.__wallet)

    def pay(self, amount):
        if self.__wallet < amount:
            print("돈이 모자랍니다.")
            return
        self.__wallet -= amount

In [62]:
kms = Person4("김민수", 95, "인천", 20000)
kms.amount()
kms.pay(10000)

20000


In [93]:
#tibbers -> 매서드, Annie -> 클래스

class Annie:
    def __init__(self, HP, mana, AP):
        self.HP = HP
        self.mana = mana
        self.AP = AP

    def tibbers(self):
        print(self.AP * 0.65 + 400)

In [ ]:
a = Annie(*list(map(float,input("체력, 마나, AP를 입력하세요.").split(" "))))
a.tibbers()

In [87]:
class Annie:
    def __init__(self, HP, mana, AP):
        self.HP = HP
        self.mana = mana
        self.AP = AP

    def tibbers(self):
        print(f'티버: 피해량 {self.AP * 0.65 + 400}')



In [ ]:
HP, mana, AP = map(float, input("체력, 마나 , AP를 입력하세요.").split)
x = Annie(AP = AP, mana = mana, HP = HP)
x.tibbers()

# NumPy(넘파이)

    1. 파이썬 내장 모듈이 아니므로 별도의 설치가 필요
    2. 숫자 데이터를 좀 더 쉽고 효과적으로 다룰 수 있음.
    3. 다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원.
    4. 배열(array) : 순서가 있는 같은 종류(type)의 데이터가 저장되는 자료형
    5. 벡터화 연산(vectorized operation)

#### Numpy Array VS Python List
    
    1. Numpy Array : data, deimensions, strides(type 고정)
    2. Python List : length, items(자유로움 -> 넣었다 뺐다 바꿨다 ... / 주소를 통해 값을 가져오므로 메모리를 많이 차지하고 속도가 느림, 다양한 type으로 가지고 있을수 있음)

#### 넘파이 패키지 임포트하기

    1. import numpy as np

#### 1차원 배열 만들기

    1. ndarray는 N-dimensional Array의 약자
    2. numpy의 array 메서드 인수로 시퀀스 자료형을 넣으면 ndarray 클래스 객체, 즉 numpy배열로 변환해줌.
    3. 시퀀스 자료형은 튜플보다 주로 리스트를 많이 활용함.
    4. 정수와 실수가 혼합된 리스트라면 표현 범위가 더 큰 자료형으로 변환되어 실수 타입으로 변환함.
    5. 넘파이의 배열인 ndarray클래스는 요소가 모두 같은 자료형을 갖는다.

#### 넘파이의 자료형
    1. boolean(참 또는 거짓) : '?'
    2. int(정수) : 'i", i8(64bit)
    3. unsigned int(양수와 음수) : 'u', u8(64bit)
    4. float : 'f', f8(64bit)
    5. complex : 'c',c16(128bit)
    6. Object: 'O', 0(객체에 대한 포인터)
    7. Unicode string : 'U', U24(24 유니코드 글자)
    8. 무한대 : np.inf(infinity)
    9. 정의할 수 없는 숫자 : np.nan(not a number)

#### 벡터화 연산(Vectorized Operation)
    1. 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산을 지원함.
    2. for 반복문이 없이 연산식을 표현할수 있음.

#### 2차원 배열 만들기 
    1. 2차원 배열은 행렬(matrix)
    2. 가로줄을 행(row), 세로줄을 열(column)
    3. 리시트를 중첩하여 리스트의 리스트를 이용해서 2차원 배열처럼 생성할 수 있음.

#### 3차원 배열 만들기
    1. 3차원 배열의 구조는 '깊이 * 행 * 열'
    2. axis 0 : 깊이 / axis 1 : 행 / axis 2 : 열
    3. len(d) : 깊이 / len(d[0]) : 행 / len(d[0][0])
    4. ndim 속성과 shape 속성 :배열의 차원과 크기를 구할 수 있음.   
    5. 인덱싱과 슬라이싱

#### 배열 생성
    1. 단순한 배열을 생성하는 메서드를 제공함.
        1.1. zeros, ones : 모든 값을 0이나 1로 공간을 할당
        1.2. zeros_like, ones_like : shape의 배열을 생성하고 모든 값을 0이나 1로 할당
        1.3. empty : 공간만 할당
        1.4. arange : range의 형태로 할당
        1.5. linspace : 등간격으로 갯수대로 출력해줌.
        1.6. logspace : log 간격으로 갯수대로 출력해줌.
        1.7. flatten, ravel :  1차원 배열
    2. 속성
        2.1. transpose : 행과 열을 바꿔서 출력
        2.2. reshape : 주어진 행과 열로 나눠줌. / 뒤에 -1로 입력하면 알아서 배열을 맞춰줌
        2.3. newaxis :1차원 증가시킴
    3. 배열 연결
        3.1. hstack : 배열을 수평으로 붙여줌.
        3.2. vstack : 배열을 수직으로 붙여줌.
        3.3. dstack : 배열을 깊이로 붙여줌.
        3.4. stack : 저정한 차원(축으로) 배열을 연결 / default는 0임.
        3.5. r_ : hstack 명령과 비슷하게 배열을 좌우로 연결 / []을 사용
        3.6. c_ : 세로 배열로 연결 / []을 사용
        3.7. tile : 동일한 배열을 반복

In [102]:
import numpy as np

#### 01010101 -> 8bits == 1byte

In [111]:
ar = np.array([_ for _ in range(10)])

ar
ar.shape
print(type(ar))
ar.dtype        

<class 'numpy.ndarray'>


dtype('int64')

In [110]:
ar2 = np.array([1.2, 2, 5, 7, 6.2])

ar2     # 리스트 전체를 표현 범위가 큰 자료형인 실수형태로 출력
ar2.dtype

dtype('float64')

In [121]:
# int(정수) => 'i'
ar3 = np.array([_ for _ in range(3, 10, 3)], 'i8')   # int8bytes -- > 8*8bit
print(ar3)
print(ar3.dtype)

[3 6 9]
int64


In [116]:
# float(실수) => 'f'
ar4 = np.array([_ for _ in range(2, 10 ,2)], 'f8')
print(ar4)
print(ar4.dtype)

[2. 4. 6. 8.]
float64


In [122]:
# 'U8' 유니코드 8글자 자료형을 명시적으로 선언
#  그래서 시퀀스 자료형 중 제일 큰 값이 <U5이지만 <U8
ar5 = np.array(["가나다라마", "바사아", "자", "차카"], 'U5')
print(ar5)
print(ar5.dtype)
# U8은 최대 8글자의 유니코드 자료형이다.

['가나다라마' '바사아' '자' '차카']
<U5


In [125]:
x = np.array([1, 2, 3], dtype = 'f')
x.dtype
x[0] + x[1]

3.0

In [126]:
x = np.array([1, 2, 3], dtype = 'U')
x.dtype
x[0] + x[1]

'12'

In [ ]:
list_samp = [_ for _ in range(3)]
print(list_samp * 5)

In [136]:
# 2차원 배열
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

2 * a + b
a == 2
b > 10
(a == 2) & (b > 10)

array([False,  True, False])

In [141]:
# 2차원 배열
c = np.array([[1,2,3],
             [4 ,5, 6]])

c
c.shape
len(c)
len(c[0])

3

In [143]:
# 2차원 배열
d = np.array([[_ for _ in range(10,50,10)],
             [_ for _ in range(50,90,10)]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [149]:
# 3차원 배열 
# 2 * 3 * 4
d = np.array([[[1, 2, 3, 4], 
                [5, 6, 7, 8],
                [9, 10, 11, 12]],
                [[13, 14, 15, 16],
                [17, 18, 19, 20],
                [21, 22, 23, 23]]])

d           # 깊이
d[0]        # 행
d[0][0]     # 열

array([1, 2, 3, 4])

In [151]:
# 1차원 인덱싱
a = np.array([_ for _ in range(5)])

a[2]

2

In [155]:
# 다차원 인덱싱
a = np.array([[0, 1, 2], [3, 4, 5]])
a[0,2]      # x축, y축을 기준으로 인덱싱

2

In [159]:
# 다차원 슬라이싱
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a[0, :]     # 첫번째 행 전체
a[:, 1]     # 두번째 열 전체
a[1, 1:]    # 두번째 행의 두번째 열부터 끝열까지
a[:2, :2]   # 


array([[0, 1],
       [4, 5]])

In [166]:
np.array([_ for _ in range(8)]).reshape(2, 4)


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [185]:
m = np.array([_ for _ in range(15)]).reshape(3, 5)

m[1,2]      # 1번째 행, 2번째 열
m[2,4]      # 2번째 행, 4번째 열
m[1, 1:3]   # 1번째 행, 1번째 열에서 2번째 열 까지 슬라이싱
m[1:, 2]    # 1, 2번째 행, 2번째 열 슬라이싱
m[:2, 3:]   # 0, 1번째 행, 3번째 이상 열 슬라이싱

array([[3, 4],
       [8, 9]])

In [186]:
# zeros 메서드
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [192]:
# zeros 문자열 메서드
c = np.zeros(5, dtype='U4')
c

array(['', '', '', '', ''], dtype='<U4')

In [194]:
# zeros 문자열 메서드
c[0] = "abc"
c[1] = "abcd"
c[2] = "ABCDE"  # 유니코드 4자리수까지 입력 가능하기때문에 "E"가 빠짐.
c

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [196]:
# ones 다차원 메서드 => 1로 초기화
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [198]:
# ones_like / zeros_like 메서드
f = np.ones_like(b, dtype="f")
f

array([1., 1., 1.], dtype=float32)

In [200]:
# empty 초기화 메서드
g = np.empty((4,3))     # 배열만 생성하고 값을 초기화
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [203]:
# arrange 메서드
np.arange(10)  # 0, ... , n-1
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [211]:
# linspace 메서드
np.linspace(0, 100, 5)      # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [212]:
np.logspace(0, 100, 5)


array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [214]:
# transpose 속성
A = np.array([[1, 2, 3], [4, 5, 6]])    # 2 * 3 배열
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [216]:
# reshape 속성
ex3 = np.arange(12)
ex3.reshape(3, 4)       # 3개의 행, 4개의 열

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [217]:
# reshape 속성
ex3 = np.arange(12)
ex3.reshape(3, -1)      # 음수도 가능하여 자동적으로 배열해줌.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [221]:
# flatten 또는 ravel 메서드 -> 1차원을 만들어줌.
ex3.flatten()
ex3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [223]:
# newaxis 메서드


AttributeError: 'numpy.ndarray' object has no attribute 'newaxis'

In [228]:
# hstack 명령
# 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더많은 배열을 만듬.
a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))

print(a1)
print(a2)
np.hstack([a1, a2])

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [227]:
# vstack 명령
# 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열을 만듬.
b1 = np.ones((2, 3))
b2 = np.zeros((3, 3))

print(b1)
print(b2)
np.vstack([b1, b2])

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [230]:
# dstack 명령
# 제3의 축(깊이) 방향으로 배열을 합침.
c1 = np.ones((3, 4))        # 3 * 4
c2 = np.zeros((3, 4))       # 3 * 4

print(c1)
print(c2)
np.dstack([c1, c2])         # 3 * 4 * 2

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [232]:
# stack 명령
# 사용자가 지정한 차원(축 = axis)으로 배열을 연결
c = np.stack([c1, c2])      # axis = 0이므로 2인 차원이 추가되어 2 * 3 * 4
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [236]:
# stack 명령
c = np.stack([c1, c2], axis=1)      # axis = 0 이면 깊이, axis = 1이면 행, axis = 2이면 열 
c                                   # axis = 1일때, 3 * 4 -> 3 * 2 * 4 / axis = 2일때, 3 * 4 * 2

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [242]:
# r_ 메서드
# hstack명령과 비슷하게 배열을 좌우로 연결
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [241]:
# c_ 메서드
# 배열의 차원을 증가시킨 후 좌우로 연결함.
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [246]:
# tile 명령
# 동일한 배열을 반복하여 연결
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [247]:
# tile 명령
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [291]:
a = np.zeros((3, 3))
a
b = np.ones((3, 2))
b
c = np.arange(10,160,10)
c.reshape(3, 5)

ab = np.hstack([a, b])
abc = np.vstack([ab, c])
abc = np.tile

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [292]:
a = np.zeros((3, 3))
a
b = np.ones((3, 2))
b
c = np.array(_ for _ in range(10,160,10))
c

ab = np.hstack([a, b])
ab
np.

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])